### ISSUE TITLE
enable CONFIG_LV_USE_FS_ARDUINO_ESP_LITTLEFS=y. BUILD ERROR!!!

### ISSUE THREAD

**Issue by ngowangvinh** [kisvegabor/lvgl#7527]
### LVGL version

v9.2.2

### Platform

ESP-IDF 5.3.2 (using VScode extension)
Arduino 3.1.0~1 as component
lvgl 9.2.2 as component

### What happened?

Error when build:
 ```
W:/ESP_IDF/project/test_lvgl_lovy_esp32_wrover/managed_components/lvgl__lvgl/src/libs/fsdrv/lv_fs_arduino_esp_littlefs.cpp:5:10: fatal error: LittleFS.h: No such file or directory
    5 | #include "LittleFS.h"
```

### How to reproduce?

ADD Arduino and lvgl as components in ESP-IDF VSCODE Extension project.
```
dependencies:
  idf:
    version: '>=4.1.0' 
  espressif/arduino-esp32: ^3.1.0~1
  lvgl/lvgl: ^9.2.2
```
set sdkconfig:
```
CONFIG_LV_FS_DEFAULT_DRIVE_LETTER=70
CONFIG_LV_USE_FS_ARDUINO_ESP_LITTLEFS=y
CONFIG_LV_FS_ARDUINO_ESP_LITTLEFS_LETTER=70
```
Build project -> error occur!
